imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: visualnet_config.yml }

# Twig Configuration
twig:
    debug:            true
    strict_variables: %kernel.debug% 
    globals:
        langs: %langs%
        validator: %validator%
        vr_version: "1.8.4"


framework:
    #esi:             ~
    translator:      { fallback: pl }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        storage_id:     visualnet.session.storage 
        default_locale: pl
        auto_start:     true   

sensio_framework_extra:
    router:  { annotations: true }
    request: { converters: true }
    view:    { annotations: true }
    cache:   { annotations: true }

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
#    filters:
#      yui_js:
#        jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
#    java: C:\\Program Files\\Java\\jre6\\bin\\java.exe
#    filters:
#        yui_css:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
#        yui_js:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

propel:
  
    path:       "%kernel.root_dir%/../vendor/propel"
    phing_path: "%kernel.root_dir%/../vendor/phing"
  
    dbal:
        driver:               mysql
        user:                 root
        password:             null
        dsn:                  mysql:host=localhost;dbname=recruiter;charset=UTF8
        options:              {}
        attributes:           {}

gregwar_captcha: ~

# Swiftmailer Configuration
swiftmailer:
    transport: smtp
    host:      smtp.wojciech-kowalik.pl
    port:      587
    username:  kontakt@wojciech-kowalik.pl
    password:  kochanieAK329
    spool:
        type: file
        path: "%kernel.root_dir%/spool" 

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: dir # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
        
services:
   twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }
   twig.extension.debug:
       class: Twig_Extensions_Extension_Debug
       tags:
           - { name: twig.extension }        