parameters:
#    form.example.class: Visualnet\VisualRecruiter\FormBundle\Example

services:
#    form.example:
#        class: %form.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
